# Generated by Django 3.2.9 on 2022-02-01 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='blogApp.author'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTitle', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('user_email', models.EmailField(blank=True, max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogApp.post')),
            ],
        ),
    ]
